version: '3.1'
services:
  web:
    image: php:apache
    container_name: test1
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
      
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - my-bridge-network 
  api:
    image: biss
    container_name: test1_api
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - my-bridge-network
    
volumes:
  my-bridge-network:
  